const PRIMARY = "PRIMARY KEY",
    UNIQUE = "UNIQUE",
    INDEX = "INDEX",
    FULLTEXT = "FULLTEXT";

exports.PRIMARY = PRIMARY;
exports.UNIQUE = UNIQUE;
exports.INDEX = INDEX;
exports.FULLTEXT = FULLTEXT;
