/** Numeric **/
const TINYINT = "TINYINT",
    SMALLINT = "SMALLINT",
    MEDIUMINT = "MEDIUMINT",
    INT = "INT",
    BIGINT = "BIGINT",
    DECIMAL = "DECIMAL",
    FLOAT = "FLOAT",
    DOUBLE = "DOUBLE",
    REAL = "REAL",
    BIT = "BIT",
    BOOLEAN = "BOOLEAN",
    SERIAL = "SERIAL";

/** Date and Time **/
const DATE = "DATE",
    DATETIME = "DATETIME",
    TIMESTAMP = "TIMESTAMP",
    TIME = "TIME",
    YEAR = "YEAR";

/** String **/
const CHAR = "CHAR",
    VARCHAR = "VARCHAR",
    TINYTEXT = "TINYTEXT",
    MEDIUMTEXT = "MEDIUMTEXT",
    LONGTEXT = "LONGTEXT",
    BINARY = "BINARY",
    VARBINARY = "VARBINARY",
    TINYBLOB = "TINYBLOB",
    MEDIUMBLOB = "MEDIUMBLOB",
    BLOB = "BLOB",
    LONGBLOB = "LONGBLOB",
    ENUM = "ENUM",
    SET = "SET";

/** Spatial **/
const GEOMETRY = "GEOMETRY",
    POINT = "POINT",
    LINESTRING = "LINESTRING",
    POLYGON = "POLYGON",
    MULTIPOINT = "MULTIPOINT",
    MULTILINESTRING = "MULTILINESTRING",
    MULTIPOLYGON = "MULTIPOLYGON",
    GEOMETRYCOLLECTION = "GEOMETRYCOLLECTION";

/** Other **/
const JSON = "JSON";

/** Exports **/
exports.TINYINT = TINYINT;
exports.SMALLINT = SMALLINT;
exports.MEDIUMINT = MEDIUMINT;
exports.INT = INT;
exports.BIGINT = BIGINT;
exports.DECIMAL = DECIMAL;
exports.FLOAT = FLOAT;
exports.DOUBLE = DOUBLE;
exports.REAL = REAL;
exports.BIT = BIT;
exports.BOOLEAN = BOOLEAN;
exports.SERIAL = SERIAL;

exports.DATE = DATE;
exports.DATETIME = DATETIME;
exports.TIMESTAMP = TIMESTAMP;
exports.TIME = TIME;
exports.YEAR = YEAR;

exports.CHAR = CHAR;
exports.VARCHAR = VARCHAR;
exports.TINYTEXT = TINYTEXT;
exports.MEDIUMTEXT = MEDIUMTEXT;
exports.LONGTEXT = LONGTEXT;
exports.BINARY = BINARY;
exports.VARBINARY = VARBINARY;
exports.TINYBLOB = TINYBLOB;
exports.MEDIUMBLOB = MEDIUMBLOB;
exports.BLOB = BLOB;
exports.LONGBLOB = LONGBLOB;
exports.ENUM = ENUM;
exports.SET = SET;

exports.GEOMETRY = GEOMETRY;
exports.POINT = POINT;
exports.LINESTRING = LINESTRING;
exports.POLYGON = POLYGON;
exports.MULTIPOINT = MULTIPOINT;
exports.MULTILINESTRING = MULTILINESTRING;
exports.MULTIPOLYGON = MULTIPOLYGON;
exports.GEOMETRYCOLLECTION = GEOMETRYCOLLECTION;

exports.JSON = JSON;